version: "3.4"

services:
  stapes:
    restart: always
    image: stapes
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 1337:1337
    networks:
      - stapes-network
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 38000:27017
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - stapes-network
    volumes:
      - /data/db:/data/db

networks:
  stapes-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
